// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgtb9GsixlLqzNyzrxXxRr94_hj0a8OVA',
    appId: '1:717675957615:web:13c38cc0de5c9048f22c9a',
    messagingSenderId: '717675957615',
    projectId: 'datn-version2-eaa5c',
    authDomain: 'datn-version2-eaa5c.firebaseapp.com',
    storageBucket: 'datn-version2-eaa5c.firebasestorage.app',
    measurementId: 'G-QGR2V0TLM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9M42r-pOBupAa87M0lncwQB9UsAkv-sI',
    appId: '1:717675957615:android:f4a1927dd11de4aef22c9a',
    messagingSenderId: '717675957615',
    projectId: 'datn-version2-eaa5c',
    storageBucket: 'datn-version2-eaa5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm2X-JLPfCVMUt5dUKK9WykFGtEf6DAVU',
    appId: '1:717675957615:ios:443d8ef2996ed7a5f22c9a',
    messagingSenderId: '717675957615',
    projectId: 'datn-version2-eaa5c',
    storageBucket: 'datn-version2-eaa5c.firebasestorage.app',
    iosBundleId: 'com.example.datnVersion2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm2X-JLPfCVMUt5dUKK9WykFGtEf6DAVU',
    appId: '1:717675957615:ios:443d8ef2996ed7a5f22c9a',
    messagingSenderId: '717675957615',
    projectId: 'datn-version2-eaa5c',
    storageBucket: 'datn-version2-eaa5c.firebasestorage.app',
    iosBundleId: 'com.example.datnVersion2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgtb9GsixlLqzNyzrxXxRr94_hj0a8OVA',
    appId: '1:717675957615:web:73f06da7e37e52f1f22c9a',
    messagingSenderId: '717675957615',
    projectId: 'datn-version2-eaa5c',
    authDomain: 'datn-version2-eaa5c.firebaseapp.com',
    storageBucket: 'datn-version2-eaa5c.firebasestorage.app',
    measurementId: 'G-8JG70YN301',
  );
}
